### ISSUE TITLE
How to specify ethercat master path?

### ISSUE THREAD

**Issue by rene-dev** [sittner/linuxcnc-ethercat#33]
how do I specify a custom path for the ethercat master with your build system?
at the moment I hacked this into this file: https://github.com/sittner/linuxcnc-ethercat/blob/2d269c58a419f990ae7ba7acdf8946aa9c823c85/src/realtime.mk#L27
is there a proper way?

**Comment by sirop** [comment]
@rene-dev 
This is the wrong  repo to put up this question as the EtherCAT master is built within https://github.com/sittner/ec-debianize .

**Comment by rene-dev** [comment]
Im not using the deb package, I compile it using the makefile.

**Comment by sittner** [comment]
Currently the build scripts need the master to be installed system wide.
