### ISSUE TITLE
EL6900 configuration

### ISSUE THREAD

**Issue by robochime** [sittner/linuxcnc-ethercat#67]
Good morning, Sittner, if you can help me, I'm using EL6900 with two EL1904 inputs and one EL2904 output as your configuration, I think you should load the program first through TWINCAT3 in EL6090, but it does not work in linuxcnc, you can open your TwinSAFE example - project.xml in TWIN-CAT3 and download it in the EL6900 with no errors in sight, can you give me an orientation on this topic? Thank you.

-I have open TwinSAFE-project.xml and installed on the EL6900
-I have an error in TWINCAT3 led diag4 Communication error in one of the TwinSAFE
groups
-The errors are in the configuration EL1904 and EL2904, how to configure them?
status 0x68
diag 0x85
Up to here it is solved !!!!

now I have to fix the error in linuxcnc,
I have an error registering the PDO.

Error 0xF101: 01 not assigned ...

The6900
El1904
El1904
El2904
SafeOP + Error

error Sync manager watchdog

This is how it works!

error led diag4 error in groups

**Comment by liuzq71** [comment]
hi robochime,

i want to write driver for my Inovance IS620N servo imitate lcec_deasda.c, can you give me some suggestions because i find some differences between  IS620N  and asda-a2-e?
thanks

**Comment by liuzq71** [comment]
hi sittner,

which series servo is used in swm-fm45a projects? is asda A2-E?thanks

**Comment by robochime** [comment]
hello liuzq71, not used any of the two servodriver that you mention, but they are different models and it is normal that it is not the same, I recommend that you write a new modified controller the existing ASDA, you will have to look at the manuals to see the PDO , and how to configure the driver, I can not help you much but I hope it works for you, Regards
