### ISSUE TITLE
patches for linuxcnc - 2.8 / 2.9

### ISSUE THREAD

**Issue by robochime** [sittner/linuxcnc-ethercat#76]
hello sittner could you tell me how to configure the patch for linuxcnc branches 2.8 / 2.9? , Thank you.

**Comment by narogon** [comment]
Here are patch files for 2.8 version 2.8.0~pre1. I don't know if they continue working for new versions. 

[patch linux2.8.zip](https://github.com/sittner/linuxcnc-ethercat/files/3729975/patch.linux2.8.zip)

**Comment by sittner** [comment]
I think we should try to get the required change to be integrated in the upstream version. I will create a pull request for this on the lcnc git repro this week.

**Comment by robochime** [comment]
Hi Naragon, thank you very much for the patch.
Hi Sittner, thank you very much for answering, I know you are very busy, I think it is a good idea, I will try to help in any way I can, thanks.

**Comment by robochime** [comment]
Hi, the patches are working fine on the linuxcnc master branch, thanks.
