### ISSUE TITLE
problem with the integration of the ectty.h library

### ISSUE THREAD

**Issue by robochime** [sittner/linuxcnc-ethercat#96]
Good morning, if you can help me, I integrated the library using #include "../include/ectty.h" the compilation is correct, but when I start lcec.so I have symbols inflicted in ectty_tx_data, I have to modify the realtime.mk file no ? could you help me with that? thanks.

**Comment by sirop** [comment]
More info would be helpful.
Please show your installations steps.

**Comment by robochime** [comment]
Sirop time,
install ec-debianize with option `--enable-tty`, then modify the tty example to work EL6001, it works fine, now I want to integrate it into linuxcnc-ethercat, created a new one called EL6001, and I can bring it to OP, I want to integrate the library TTY, in the EL6001.C file I include the `"../include/ectty.h"` library and linuxcnc-ethercat compiles well, when I start linuxcnc it gives me the following start lcec.so I have symbols inflicted in ectty_tx_data

**Comment by sirop** [comment]
Copy-paste this error message please.

**Comment by robochime** [comment]
![Captura de pantalla de 2020-11-08 13-33-41](https://user-images.githubusercontent.com/26814972/98465486-982a8a80-21c9-11eb-9fa5-94b9f821444c.png)

**Comment by sirop** [comment]
Frankly speaking, I do not know what to do here. Maybe, add _"../include/ectty.h"_ to EXTRA_CFLAGS ...

**Comment by robochime** [comment]
Hello @sirop 
not working at the moment, but thank you very much for the help.

**Comment by robochime** [comment]
![Captura de pantalla de 2020-11-22 20-33-16](https://user-images.githubusercontent.com/26814972/99915152-30fcf200-2d02-11eb-9917-862716d44e90.png)
![Captura de pantalla de 2020-11-22 20-33-37](https://user-images.githubusercontent.com/26814972/99915155-32c6b580-2d02-11eb-9392-aad08f6051c8.png)
![Captura de pantalla de 2020-11-22 20-40-53](https://user-images.githubusercontent.com/26814972/99915281-15deb200-2d03-11eb-8111-64c654199c42.png)

Hello @sirop 
Can I ask you in which file would you add " "../include/ectty.h" a EXTRA_CFLAGS ."

user .mk? realtime.mk?, tried various things seen on the internet, but not which way is correct?


thanks

**Comment by sirop** [comment]
You can try user.mk , but what about this:

> I have successfully tested the tty example from ethercat master, but it is
> designed for a kernelspace cyclic task only.
> 
> How can I modify this example to use a Beckhoff EL6002 with my ethercat cyclic
> task in userspace ?

https://etherlab-users.etherlab.narkive.com/4jqS34Oc/virtual-tty-el6002-with-ethercat-in-userspace

**Comment by robochime** [comment]
Hello @sirop , if I sent you an email but I have no response, I did not find any example in linuxcnc-ethercat, it may be that you are posing it wrong.
Tanks

**Comment by sirop** [comment]
@robochime 
You can try smth. like this, but it is more important to answer first Sebastien Blanchet's question
from https://etherlab-users.etherlab.narkive.com/4jqS34Oc/virtual-tty-el6002-with-ethercat-in-userspace .

**Comment by robochime** [comment]
Hello @sirop 
the answer to the question, the virtual TTY only works in KERNEL mode it does not work is USER SPACE

**Comment by sirop** [comment]
@robochime 
But you build linuxcnc-ethercat  (lcec.so) for userspace, so as I understand it, you can neither build nor use TTY in userspace.

**Comment by robochime** [comment]
Hi @sirop, 
Hi, I'll have to find another way to use serial transmission in user mode, thank you very much
